repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.89.1
    hooks:
      - id: terraform_fmt
        files: 'infra/.*|modules/.*'
        args:
          - --args=-diff
          - --args=-check
    
      - id: terraform_docs
        files: 'infra/.*|modules/.*'
        args:
          - '--args=--lockfile=false'
          - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
          - --hook-config=--add-to-existing-file=true     # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
          - --hook-config=--files=./*infra/!(migrations)/* # Exclude infra/migrations directory

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Not sure we need this
      # - id: end-of-file-fixer
      #   files: 'infra/.*|modules/.*'
      - id: trailing-whitespace
        files: 'infra/.*|modules/.*'
      - id: detect-aws-credentials
      - id: detect-private-key
  # Gitleaks is a SAST tool for detecting and preventing hardcoded secrets like passwords, api keys, and tokens in git repos.
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks